version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres_visagium
      - DB_PASSWORD=postgres
      - DB_NAME=visagium_backend
      - DB_SSL_MODE=disable
      - SERVER_ADDRESS=:8080
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres_visagium
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=visagium_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
